/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_System;

/**
 *
 * @author Admin
 */
@SuppressWarnings("serial")
public class RestaurantManagementSystem extends javax.swing.JFrame {
     double firstnum;
    double secondnum;
    double result;
    double  i[] =new double [4];
    
    
   
    private char math_operator;
    String operations;
    double German_sterlling = 1.23;
    double SouthAfrican_rands = 1.90;
     double US_Dollar = 0.89;
    double Ruandan_shillings = 300.75;
    double kenyan_shilling = 1.20;
    double Japaness_Yen = 4.96;
    
    
    
    
    public RestaurantManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCchickenBurger = new javax.swing.JCheckBox();
        jCbacon = new javax.swing.JCheckBox();
        jCChickenBurgerMeal = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jcmbDrink = new javax.swing.JComboBox<String>();
        jCTax = new javax.swing.JCheckBox();
        jCDelivery = new javax.swing.JCheckBox();
        jtxtChickenBurgerMeal = new javax.swing.JTextField();
        jtxtchickenburger = new javax.swing.JTextField();
        jtxtBacon = new javax.swing.JTextField();
        jlbconvert = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCmbcurrency = new javax.swing.JComboBox<String>();
        jtxtconvert = new javax.swing.JTextField();
        jbtnConvert = new javax.swing.JToggleButton();
        jbtnClose = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jlblCostofMeals = new javax.swing.JLabel();
        jlblCostofdrinks = new javax.swing.JLabel();
        jlblCostofdelivery = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblSubtotal = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlbtotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtarearcpt = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jtxtFieldcalc = new javax.swing.JTextField();
        jbtnbsp = new javax.swing.JToggleButton();
        jbtnclear = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jbtnAddn = new javax.swing.JToggleButton();
        jbtn9 = new javax.swing.JToggleButton();
        jbtn5 = new javax.swing.JToggleButton();
        jbtn4 = new javax.swing.JToggleButton();
        jbtnmultiply = new javax.swing.JToggleButton();
        jbtn3 = new javax.swing.JToggleButton();
        jbtn2 = new javax.swing.JToggleButton();
        jbtn1 = new javax.swing.JToggleButton();
        jbtndiv = new javax.swing.JToggleButton();
        jbtn0 = new javax.swing.JToggleButton();
        jbtnpoint = new javax.swing.JToggleButton();
        jbtnequals = new javax.swing.JToggleButton();
        jbtn6 = new javax.swing.JToggleButton();
        jbtn8 = new javax.swing.JToggleButton();
        jbtn7 = new javax.swing.JToggleButton();
        jbtnsubtract = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbtntotal = new javax.swing.JToggleButton();
        jbtnExit = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCchickenBurger.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCchickenBurger.setText("Chicken Burger");
        jCchickenBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCchickenBurgerMouseClicked(evt);
            }
        });
        jCchickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCchickenBurgerActionPerformed(evt);
            }
        });

        jCbacon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCbacon.setText("Bacon and Cheese Burger");
        jCbacon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbaconMouseClicked(evt);
            }
        });

        jCChickenBurgerMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCChickenBurgerMeal.setText("Chicken Burger Meal");
        jCChickenBurgerMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCChickenBurgerMealMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Drinks");

        jcmbDrink.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jcmbDrink.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Drink", "water", "porridge", "coffee", "wine", "afia_juice" }));
        jcmbDrink.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jcmbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDrinkActionPerformed(evt);
            }
        });

        jCTax.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCTax.setText("Tax");
        jCTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCTaxMouseClicked(evt);
            }
        });

        jCDelivery.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCDelivery.setText("Home Delivery");
        jCDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCDeliveryMouseClicked(evt);
            }
        });
        jCDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDeliveryActionPerformed(evt);
            }
        });

        jtxtChickenBurgerMeal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtChickenBurgerMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurgerMeal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtchickenburger.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtchickenburger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtchickenburger.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtBacon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtBacon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBacon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbconvert.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlbconvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCTax, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jCDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCbacon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCChickenBurgerMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCchickenBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtChickenBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtchickenburger, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbconvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCchickenBurger)
                    .addComponent(jtxtchickenburger, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCChickenBurgerMeal)
                    .addComponent(jtxtChickenBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCbacon)
                    .addComponent(jtxtBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCTax)
                    .addComponent(jCDelivery))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jlbconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jCmbcurrency.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCmbcurrency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Currency", "USA ", "SouthAfrica", "Ruanda", "Brazil" }));
        jCmbcurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbcurrencyActionPerformed(evt);
            }
        });

        jtxtconvert.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtxtconvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbtnConvert.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnConvert.setText("Convert");
        jbtnConvert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConvertActionPerformed(evt);
            }
        });

        jbtnClose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnClose.setText("Close");
        jbtnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtconvert)
                    .addComponent(jCmbcurrency, 0, 182, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCmbcurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblCostofMeals.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jlblCostofMeals.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCostofMeals.setText("0");
        jlblCostofMeals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblCostofdrinks.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jlblCostofdrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblCostofdelivery.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jlblCostofdelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Cost Of Drink");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Cost of Meals");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Cost of Delivery");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblCostofMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCostofdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCostofdelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jlblCostofdrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblCostofMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostofdelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Sub Total:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Tax:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Total");

        jlblSubtotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSubtotal.setText("0");
        jlblSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jlblTax.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTax.setText("0");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jlblTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblTaxMouseClicked(evt);
            }
        });

        jlbtotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlbtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtarearcpt.setColumns(20);
        jtxtarearcpt.setRows(5);
        jScrollPane1.setViewportView(jtxtarearcpt);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receipt", jPanel7);

        jtxtFieldcalc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtFieldcalc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtFieldcalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldcalcActionPerformed(evt);
            }
        });

        jbtnbsp.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnbsp.setText("<-");
        jbtnbsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbspActionPerformed(evt);
            }
        });

        jbtnclear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnclear.setText("C");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jToggleButton16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButton16.setText("+/-");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        jbtnAddn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnAddn.setText("+");
        jbtnAddn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddnActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtnmultiply.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnmultiply.setText("*");
        jbtnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiplyActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtndiv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtndiv.setText("/");
        jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnpoint.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnpoint.setText(".");
        jbtnpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpointActionPerformed(evt);
            }
        });

        jbtnequals.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnequals.setText("=");
        jbtnequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequalsActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtnsubtract.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnsubtract.setText("-");
        jbtnsubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsubtractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtFieldcalc)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnbsp, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addComponent(jbtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbtnpoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnsubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnAddn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtFieldcalc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnbsp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnAddn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnsubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("calculator", jPanel8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6.setText("RESTAURANT MANAGEMENT SYSTEM");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jbtntotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtntotal.setText("TOTAL");
        jbtntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntotalActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jToggleButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jToggleButton5.setText("RECEIPT");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jToggleButton6.setText("RESET");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jbtntotal)
                .addGap(74, 74, 74)
                .addComponent(jToggleButton5)
                .addGap(116, 116, 116)
                .addComponent(jToggleButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnExit)
                .addGap(69, 69, 69))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtntotal)
                    .addComponent(jbtnExit)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDrinkActionPerformed
        double water = 3.25;
        
        double porridge = 6.95;
        double coffee = 3.50;
        double wine = 10.75;
        double afia_juice = 8.35;
        
        
        if (jcmbDrink.getSelectedItem().equals("water"))
        {
            String cwater = String.format(" %.2f", water);
            jlblCostofdrinks.setText(cwater);
        }
    
        if(jcmbDrink.getSelectedItem().equals("porridge"))
        {
            String cjuice = String.format(" %.2f",porridge);
            jlblCostofdrinks.setText(cjuice);
        }
        if(jcmbDrink.getSelectedItem().equals("coffee"))
        {
            String ccoffee = String.format(" %.2f",coffee);
            jlblCostofdrinks.setText(ccoffee);
        }
        if(jcmbDrink.getSelectedItem().equals("wine"))
        {
            String csoftdrink = String.format(" %.2f",wine);
            jlblCostofdrinks.setText(csoftdrink);
        }
        if(jcmbDrink.getSelectedItem().equals("afia_juice"))
        {
            String charddrink = String.format(" %.2f",afia_juice);
            jlblCostofdrinks.setText(charddrink);
        }
        
        
        
    }//GEN-LAST:event_jcmbDrinkActionPerformed

    private void jbtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvertActionPerformed
double German_sterlling =Double.parseDouble(jtxtconvert.getText());
        if (jCmbcurrency.getSelectedItem().equals("Ruandan_shillings")) 
        {
            String cConvert1 = String.format("Ush%.2f", German_sterlling * Ruandan_shillings);
            jlbconvert.setText(cConvert1);
            
        
        }
          if (jCmbcurrency.getSelectedItem().equals("Japaness_Yen")) 
        {
            String cConvert2 = String.format("Jap%.2f", German_sterlling * Japaness_Yen);
            jlbconvert.setText(cConvert2);
            
        }
             if (jCmbcurrency.getSelectedItem().equals("SouthAfrican_rands")) 
        {
            String cConvert3 = String.format("S%.2f", German_sterlling * SouthAfrican_rands);
             jlbconvert.setText(cConvert3);
            
        }
        
    }//GEN-LAST:event_jbtnConvertActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jCDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDeliveryActionPerformed
      
    }//GEN-LAST:event_jCDeliveryActionPerformed

    private void jCDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCDeliveryMouseClicked
          double iDelivery = 5.00;
        if (jCDelivery.isSelected())
        {
            String pDelivery = String.format(" %.2f" , iDelivery);
            jlblCostofdelivery.setText(pDelivery);
            
        }
        else{
            jlblCostofdelivery.setText(null);
        }
    }//GEN-LAST:event_jCDeliveryMouseClicked

    private void jlblTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTaxMouseClicked
      
    }//GEN-LAST:event_jlblTaxMouseClicked

    private void jCTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCTaxMouseClicked
         double total1 = Double.parseDouble(jlblCostofdrinks.getText());
         double total2 = Double.parseDouble(jlblCostofMeals.getText());
         double total3 = Double.parseDouble(jlblCostofdelivery.getText());
         double alltotal = (total1+total2+total3)*0.01;
         String itax = String.format("%.2f",alltotal);
         jlblTax.setText(itax);
    }//GEN-LAST:event_jCTaxMouseClicked

    private void jCChickenBurgerMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCChickenBurgerMealMouseClicked
        double cMeal = Double.parseDouble(jlblCostofMeals.getText());
        double ChickenBurgerMeal = Double.parseDouble(jtxtChickenBurgerMeal.getText());
        double iChickenBurgerMeal = 20.25;
        
        if (jCChickenBurgerMeal.isSelected())
        {
            i [0] = (ChickenBurgerMeal*iChickenBurgerMeal) + cMeal;
            String pMeal = String.format(" %.2f", i [0] );
            jlblCostofMeals.setText(pMeal);
            
        }
    }//GEN-LAST:event_jCChickenBurgerMealMouseClicked

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jtxtFieldcalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldcalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldcalcActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
     
          String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn1.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn1.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        }
        
        
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
      
             String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn0.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn0.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
        
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
      
         String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn2.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn2.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        }  
        
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn3.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn3.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn4.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn4.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
         String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn5.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn5.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn6.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn6.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn7.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn7.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn8.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn8.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
         String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn9.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtn9.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        } 
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
         jtxtFieldcalc.setText(null);
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtnAddnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddnActionPerformed
        firstnum =Double.parseDouble(jtxtFieldcalc.getText());
        jtxtFieldcalc.setText("");
        operations =("+");
      
    }//GEN-LAST:event_jbtnAddnActionPerformed

    private void jbtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplyActionPerformed
    firstnum =Double.parseDouble(jtxtFieldcalc.getText());
        jtxtFieldcalc.setText("");
        operations =("*");
    }//GEN-LAST:event_jbtnmultiplyActionPerformed

    private void jbtnsubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubtractActionPerformed
        firstnum =Double.parseDouble(jtxtFieldcalc.getText());
        jtxtFieldcalc.setText("");
        operations =("-");
    }//GEN-LAST:event_jbtnsubtractActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
      firstnum =Double.parseDouble(jtxtFieldcalc.getText());
        jtxtFieldcalc.setText("");
        operations =("/");
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtnpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpointActionPerformed
        
          String EnterNumber = jtxtFieldcalc.getText();
        jtxtFieldcalc.setText(EnterNumber);
        if (EnterNumber=="")
        {
            jtxtFieldcalc.setText(jbtn9.getText());
            
        }
        else
        {
            EnterNumber = jtxtFieldcalc.getText() + jbtnpoint.getText();
            jtxtFieldcalc.setText(EnterNumber);
              
        }  
        
    }//GEN-LAST:event_jbtnpointActionPerformed

    private void jbtnequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalsActionPerformed
         String answer;
       secondnum = Double.parseDouble(jtxtFieldcalc.getText());
       if (operations=="+")
       {
           result=firstnum + secondnum;
           answer =String.format("%.2f",result);
           jtxtFieldcalc.setText(answer);
       }
          else if (operations=="-")
       {
           result=firstnum - secondnum;
           answer =String.format("%.2f",result);
           jtxtFieldcalc.setText(answer);
       }
        else if (operations=="/")
       {
           result=firstnum / secondnum;
           answer =String.format("%.2f",result);
           jtxtFieldcalc.setText(answer);
       }
        else if (operations=="*")
       {
           result=firstnum * secondnum;
           answer =String.format("%.2f",result);
           jtxtFieldcalc.setText(answer);
       }
    }//GEN-LAST:event_jbtnequalsActionPerformed

    private void jCchickenBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCchickenBurgerMouseClicked
double cMeal = Double.parseDouble(jlblCostofMeals.getText());
double Burger = Double.parseDouble(jtxtchickenburger.getText());
double iBurger = 25.89;
if(jCchickenBurger.isSelected()){
    i [0] = (Burger * iBurger) + cMeal;
    String pMeal = String.format("%.2f", i [0]);
    jlblCostofMeals.setText(pMeal);
}
        
    }//GEN-LAST:event_jCchickenBurgerMouseClicked

    private void jCchickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCchickenBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCchickenBurgerActionPerformed

    private void jCmbcurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbcurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbcurrencyActionPerformed

    private void jCbaconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbaconMouseClicked
      double cMeal = Double.parseDouble(jlblCostofMeals.getText());
        double Bacon = Double.parseDouble(jtxtBacon.getText());
        double ibacon = 15.20;
        
        if (jCbacon.isSelected())
        {
            i [0] = (Bacon * ibacon) + cMeal;
            String pMeal = String.format(" %.2f", i [0] );
            jlblCostofMeals.setText(pMeal);
            
        }
    }//GEN-LAST:event_jCbaconMouseClicked

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        double item1 = Double.parseDouble(jtxtchickenburger.getText());
        double item2  = Double.parseDouble(jtxtChickenBurgerMeal.getText());
        double item3 = Double .parseDouble(jtxtBacon.getText());
        double ite4 = Double .parseDouble(jlblCostofMeals.getText());
        double item5 = Double.parseDouble(jlblCostofdrinks.getText());
        double item6 = Double.parseDouble(jlblCostofdelivery.getText());
        double item7 = Double.parseDouble(jlblTax.getText());
        double item8 = Double.parseDouble(jlblSubtotal.getText());
        double item9 = Double.parseDouble(jlbtotal.getText());
        
        
        jtxtarearcpt.append("\t RESTAURANT MANAGEMENT SYTEMS:\n\n"  
                + "Chicken Burger: \t"+
              +  item1 + "\n Chicken Burger Meal: \t\t"
               + item2+"\n Bacon and Cheese Burger:\t\t"
              +  item3+"\n Cost of Meals:\t\t"
                        
               + item5+ "\n Cost of Delivery:\t\t"
               +item6+ "\n Tax:\t\t"
               +  item7+ "\n Sub Total\t\t"
               +   item8+ "\n Total\t\t"
               + item9 + "\n\n\t THANK YOU FOR SHOPPING WITH US,COME AGAIN.\n@Served by Mourice");
               
        
        
        
        
        
        
        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed

        jCmbcurrency.setSelectedIndex(0);
       jtxtconvert.setText("");
       jlbconvert.setText(null);
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        jCChickenBurgerMeal.setSelected(false);
        jCDelivery.setSelected(false);
        jtxtarearcpt.setText(null);
        jCbacon.setSelected(false);
        jcmbDrink.setSelectedIndex(0);
        jlblCostofMeals.setText("0");
        jlblCostofdrinks.setText(null);
        jlblCostofdelivery.setText(null);
        jlblSubtotal.setText("0");
        jCTax.setSelected(false);
        jlblTax.setText("0");
        jlbtotal.setText(null);
        jCchickenBurger.setSelected(false);
        jtxtBacon.setText(null);
        jtxtChickenBurgerMeal.setText(null);
        jtxtchickenburger.setText(null);
      
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jbtnbspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbspActionPerformed
      String backspace = null;
      if (jtxtFieldcalc.getText().length()>0)
      {
          StringBuilder StrB = new StringBuilder(jtxtFieldcalc.getText());
          StrB.deleteCharAt(jtxtFieldcalc.getText().length()-1);
          backspace = StrB.toString();
          jtxtFieldcalc.setText(backspace);
          
          
          
      }
    }//GEN-LAST:event_jbtnbspActionPerformed

    private void jbtntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntotalActionPerformed
      double cTotal1 = Double.parseDouble(jlblCostofdrinks.getText());
      double cTotal2 = Double.parseDouble(jlblCostofMeals.getText());
      double cTotal3 = Double.parseDouble(jlblCostofdelivery.getText());
       double cTotal4 = Double.parseDouble(jlblTax.getText());
      double SubTotal = (cTotal1+cTotal2+cTotal3);
      String iSubTotal = String.format("%.2f", SubTotal);
      jlblSubtotal.setText(iSubTotal);
      double allTotal = (cTotal1+cTotal2+cTotal3+cTotal4);
      String iTotal = String.format("%.2f", allTotal);
      jlbtotal.setText(iTotal);
       String iTotalTax = String.format("%.2f", cTotal4);
      jlblTax.setText(iTotalTax);
    }//GEN-LAST:event_jbtntotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantManagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCChickenBurgerMeal;
    private javax.swing.JCheckBox jCDelivery;
    private javax.swing.JCheckBox jCTax;
    private javax.swing.JCheckBox jCbacon;
    private javax.swing.JCheckBox jCchickenBurger;
    private javax.swing.JComboBox<String> jCmbcurrency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jbtn0;
    private javax.swing.JToggleButton jbtn1;
    private javax.swing.JToggleButton jbtn2;
    private javax.swing.JToggleButton jbtn3;
    private javax.swing.JToggleButton jbtn4;
    private javax.swing.JToggleButton jbtn5;
    private javax.swing.JToggleButton jbtn6;
    private javax.swing.JToggleButton jbtn7;
    private javax.swing.JToggleButton jbtn8;
    private javax.swing.JToggleButton jbtn9;
    private javax.swing.JToggleButton jbtnAddn;
    private javax.swing.JToggleButton jbtnClose;
    private javax.swing.JToggleButton jbtnConvert;
    private javax.swing.JToggleButton jbtnExit;
    private javax.swing.JToggleButton jbtnbsp;
    private javax.swing.JToggleButton jbtnclear;
    private javax.swing.JToggleButton jbtndiv;
    private javax.swing.JToggleButton jbtnequals;
    private javax.swing.JToggleButton jbtnmultiply;
    private javax.swing.JToggleButton jbtnpoint;
    private javax.swing.JToggleButton jbtnsubtract;
    private javax.swing.JToggleButton jbtntotal;
    private javax.swing.JComboBox<String> jcmbDrink;
    private javax.swing.JLabel jlbconvert;
    private javax.swing.JLabel jlblCostofMeals;
    private javax.swing.JLabel jlblCostofdelivery;
    private javax.swing.JLabel jlblCostofdrinks;
    private javax.swing.JLabel jlblSubtotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlbtotal;
    private javax.swing.JTextField jtxtBacon;
    private javax.swing.JTextField jtxtChickenBurgerMeal;
    private javax.swing.JTextField jtxtFieldcalc;
    private javax.swing.JTextArea jtxtarearcpt;
    private javax.swing.JTextField jtxtchickenburger;
    private javax.swing.JTextField jtxtconvert;
    // End of variables declaration//GEN-END:variables
}
